<?php

	// Allways takes a map id as first parameter (only used as base config if a second parameter is given). 
	// If a second parameter is given then it must be set to a basic group target array or null.
	// If a third parameter is given then it must be set to a basic layer target array.
	// Prints an icon-only preview button.
	// The button opens a new browser tab/window with an Origo map generated by writeConfig.php.
	// The map will show a preview of a map, a group or a layer depending on the input parameters.
	function printConfigPreviewButton($mapId, $group=null, $layer=null)
	{
		$groupInput='';
		$layerInput='';
		$titleTarget='karta (utan att skriva till disk)';
		$params=array('getHtml'=>'y', 'map'=>$mapId);
		if (isset($group))
		{
			$params['group']=$group;
			$titleTarget='grupp';
		}
		if (isset($layer))
		{
			$params['layer']=$layer;
			if (!isset($group))
			{
				$titleTarget='lager';
			}
		}
		$url='writeConfig.php?'.http_build_query($params);
		$urlJs=jsonForInlineJs($url);
		echo <<<HERE
			<button title="Förhandsgranska {$titleTarget}" aria-label="Förhandsgranska {$titleTarget}" class="updateButton historyButton" type="button" onclick='window.open({$urlJs}, "_blank");'>
				<span aria-hidden="true">&#x1F50D;&#xFE0E;</span>
			</button>
		HERE;
	}